name: vfxplayer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyqt  # Qt bindings
  - numpy>=1.26
  - opencv>=4.9
  - imageio
  - openexr      # EXR I/O
  - imath        # math lib for OpenEXR
  - opencolorio  # OCIO core library
  - py-opencolorio  # Python bindings (name on conda-forge)
  - psutil
  - pip:
      - simpleexr  # pure-Python EXR fallback
